package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/CyanAutomation/merm8/internal/api"
)

const generatedHeader = `# Code generated by go run ./scripts/generate_openapi.go; DO NOT EDIT.
# This file is generated from internal/api/openapi.go and may be removed in a future release.
`

func main() {
	spec := api.OpenAPISpec()
	raw, err := json.Marshal(spec)
	if err != nil {
		fatalf("normalize spec: %v", err)
	}
	var normalized interface{}
	if err := json.Unmarshal(raw, &normalized); err != nil {
		fatalf("normalize spec: %v", err)
	}

	jsonBytes, err := json.MarshalIndent(normalized, "", "  ")
	if err != nil {
		fatalf("marshal json: %v", err)
	}
	jsonBytes = append(jsonBytes, '\n')

	var yamlBuf bytes.Buffer
	yamlBuf.WriteString(generatedHeader)
	if err := writeYAMLValue(&yamlBuf, normalized, 0); err != nil {
		fatalf("marshal yaml: %v", err)
	}
	yamlBuf.WriteByte('\n')

	if err := writeFile("openapi.json", jsonBytes); err != nil {
		fatalf("write openapi.json: %v", err)
	}
	if err := writeFile("openapi.yaml", yamlBuf.Bytes()); err != nil {
		fatalf("write openapi.yaml: %v", err)
	}

	fmt.Println("generated openapi.json and openapi.yaml")
}

func writeYAMLValue(buf *bytes.Buffer, v interface{}, indent int) error {
	pad := strings.Repeat("  ", indent)
	switch val := v.(type) {
	case map[string]interface{}:
		keys := make([]string, 0, len(val))
		for k := range val {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := val[k]
			buf.WriteString(pad)
			buf.WriteString(yamlString(k))
			if isScalar(vv) {
				buf.WriteString(": ")
				buf.WriteString(yamlScalar(vv))
				buf.WriteByte('\n')
				continue
			}
			buf.WriteString(":\n")
			if err := writeYAMLValue(buf, vv, indent+1); err != nil {
				return err
			}
		}
	case []interface{}:
		for _, item := range val {
			buf.WriteString(pad)
			if isScalar(item) {
				buf.WriteString("- ")
				buf.WriteString(yamlScalar(item))
				buf.WriteByte('\n')
				continue
			}
			buf.WriteString("-\n")
			if err := writeYAMLValue(buf, item, indent+1); err != nil {
				return err
			}
		}
	case []string:
		for _, item := range val {
			buf.WriteString(pad)
			buf.WriteString("- ")
			buf.WriteString(yamlString(item))
			buf.WriteByte('\n')
		}
	default:
		return fmt.Errorf("unsupported type at indent %d: %T", indent, v)
	}
	return nil
}

func isScalar(v interface{}) bool {
	switch v.(type) {
	case nil, string, bool, int, int8, int16, int32, int64, float32, float64, json.Number:
		return true
	default:
		return false
	}
}

func yamlScalar(v interface{}) string {
	switch vv := v.(type) {
	case nil:
		return "null"
	case string:
		return yamlString(vv)
	case bool:
		if vv {
			return "true"
		}
		return "false"
	case int:
		return strconv.Itoa(vv)
	case int8, int16, int32, int64:
		return fmt.Sprintf("%d", vv)
	case float32, float64:
		return fmt.Sprintf("%v", vv)
	case json.Number:
		return vv.String()
	default:
		return yamlString(fmt.Sprintf("%v", vv))
	}
}

func yamlString(s string) string {
	return strconv.Quote(s)
}

func writeFile(path string, data []byte) error {
	return os.WriteFile(filepath.Clean(path), data, 0o644)
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
